export const v = {
  mint: 'url(#mint)',
  sky: 'url(#sky)',
  grass: 'url(#grass)',
  white: 'url(#white)',
  creme: 'url(#creme)',
  yellow: 'url(#yellow)',
  dark: 'url(#dark)',
  mintDark: 'url(#mintDark)',
  skyDark: 'url(#skyDark)',
  grassDark: 'url(#grassDark)',
  whiteDark: 'url(#whiteDark)',
  cremeDark: 'url(#cremeDark)',
  yellowDark: 'url(#yellowDark)',
  darkDark: 'url(#darkDark)',
}